package de.tum.cit.aet.analysis.dto.cqi;

/**
 * Summary of commit filtering results.
 *
 * @param totalCommits       Total commits before filtering
 * @param productiveCommits  Commits kept for CQI calculation
 * @param trivialCount       Commits filtered as trivial (message pattern)
 * @param autoGeneratedCount Commits filtered as auto-generated files only
 * @param emptyCount         Empty commits filtered (0 LoC)
 * @param mergeCount         Merge commits filtered
 * @param revertCount        Revert commits filtered
 * @param renameOnlyCount    Rename-only commits filtered
 * @param formatOnlyCount    Format/whitespace-only commits filtered
 * @param massReformatCount  Mass reformat commits filtered
 */
public record FilterSummaryDTO(
        int totalCommits,
        int productiveCommits,
        int trivialCount,
        int autoGeneratedCount,
        int emptyCount,
        int mergeCount,
        int revertCount,
        int renameOnlyCount,
        int formatOnlyCount,
        int massReformatCount
) {
    /**
     * Get the percentage of commits that were filtered out.
     */
    public double getFilteredPercentage() {
        if (totalCommits == 0) {
            return 0.0;
        }
        return 100.0 * (totalCommits - productiveCommits) / totalCommits;
    }

    /**
     * Get the total number of filtered commits.
     */
    public int getTotalFiltered() {
        return totalCommits - productiveCommits;
    }

    /**
     * Get summary string for logging.
     */
    public String toSummary() {
        return String.format(
                "Filtered %d/%d commits (%.0f%%): %d empty, %d merge, %d revert, %d rename, %d format, %d mass-reformat, %d generated, %d trivial",
                getTotalFiltered(), totalCommits, getFilteredPercentage(),
                emptyCount, mergeCount, revertCount, renameOnlyCount, formatOnlyCount,
                massReformatCount, autoGeneratedCount, trivialCount
        );
    }

    /**
     * Create empty summary.
     */
    public static FilterSummaryDTO empty() {
        return new FilterSummaryDTO(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
}
