package de.tum.cit.aet.analysis.dto.cqi;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Summary of commit filtering results.
 *
 * @param totalCommits       total commits before filtering
 * @param productiveCommits  commits kept for CQI calculation
 * @param trivialCount       commits filtered as trivial (message pattern)
 * @param autoGeneratedCount commits filtered as auto-generated files only
 * @param emptyCount         empty commits filtered (0 LoC)
 * @param mergeCount         merge commits filtered
 * @param revertCount        revert commits filtered
 * @param renameOnlyCount    rename-only commits filtered
 * @param formatOnlyCount    format/whitespace-only commits filtered
 * @param massReformatCount  mass reformat commits filtered
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record FilterSummaryDTO(
        int totalCommits,
        int productiveCommits,
        int trivialCount,
        int autoGeneratedCount,
        int emptyCount,
        int mergeCount,
        int revertCount,
        int renameOnlyCount,
        int formatOnlyCount,
        int massReformatCount
) {
    /**
     * Convenience constructor for loading from database with limited fields.
     */
    public FilterSummaryDTO(int totalCommits, int productiveCommits, int mergeCount,
            int trivialCount, int formatOnlyCount, int autoGeneratedCount, int emptyCount) {
        this(totalCommits, productiveCommits, trivialCount, autoGeneratedCount,
                emptyCount, mergeCount, 0, 0, formatOnlyCount, 0);
    }

    /**
     * Get the percentage of commits that were filtered out.
     */
    public double getFilteredPercentage() {
        if (totalCommits == 0) {
            return 0.0;
        }
        return 100.0 * (totalCommits - productiveCommits) / totalCommits;
    }

    /**
     * Get the total number of filtered commits.
     */
    public int getTotalFiltered() {
        return totalCommits - productiveCommits;
    }

    /**
     * Get summary string for logging.
     */
    public String toSummary() {
        return String.format(
                "Filtered %d/%d commits (%.0f%%): %d empty, %d merge, %d revert, %d rename, %d format, %d mass-reformat, %d generated, %d trivial",
                getTotalFiltered(), totalCommits, getFilteredPercentage(),
                emptyCount, mergeCount, revertCount, renameOnlyCount, formatOnlyCount,
                massReformatCount, autoGeneratedCount, trivialCount
        );
    }

    /**
     * Create empty summary.
     */
    public static FilterSummaryDTO empty() {
        return new FilterSummaryDTO(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
}
