package de.tum.cit.aet.analysis.dto.cqi;

/**
 * Summary of commit filtering results.
 *
 * @param totalCommits       Total commits before filtering
 * @param productiveCommits  Commits kept for CQI calculation
 * @param trivialCount       Commits filtered as trivial
 * @param autoGeneratedCount Commits filtered as auto-generated
 * @param copyPasteCount     Commits with reduced weight (copy-paste)
 * @param emptyCount         Empty commits filtered
 * @param mergeCount         Merge commits filtered
 */
public record FilterSummaryDTO(
        int totalCommits,
        int productiveCommits,
        int trivialCount,
        int autoGeneratedCount,
        int copyPasteCount,
        int emptyCount,
        int mergeCount
) {
    /**
     * Get the percentage of commits that were filtered out.
     */
    public double getFilteredPercentage() {
        if (totalCommits == 0) {
            return 0.0;
        }
        return 100.0 * (totalCommits - productiveCommits) / totalCommits;
    }

    /**
     * Get the total number of filtered commits.
     */
    public int getTotalFiltered() {
        return totalCommits - productiveCommits;
    }

    /**
     * Check if a significant portion was filtered.
     */
    public boolean hasSignificantFiltering() {
        return getFilteredPercentage() > 30.0;
    }

    /**
     * Get summary string for logging.
     */
    public String toSummary() {
        return String.format(
                "Filtered %d/%d commits (%.0f%%): %d trivial, %d auto-gen, %d copy-paste, %d empty, %d merge",
                getTotalFiltered(), totalCommits, getFilteredPercentage(),
                trivialCount, autoGeneratedCount, copyPasteCount, emptyCount, mergeCount
        );
    }

    /**
     * Create empty summary.
     */
    public static FilterSummaryDTO empty() {
        return new FilterSummaryDTO(0, 0, 0, 0, 0, 0, 0);
    }
}
