export interface Student {
  name: string;
  commits?: number;
  linesAdded?: number;
  linesDeleted?: number;
  linesChanged?: number;
}

export interface SubMetric {
  name: string;
  value: number;
  weight: number;
  description: string;
  details: string;
}

export interface BasicMetrics {
  totalCommits: number;
  totalLines: number;
}

// CQI Component Scores
export interface ComponentScores {
  effortBalance: number;
  locBalance: number;
  temporalSpread: number;
  ownershipSpread: number;
}

// CQI Penalty
export interface CQIPenalty {
  type: string;
  factor: number;
  reason: string;
}

// Filter Summary
export interface FilterSummary {
  totalCommits: number;
  productiveCommits: number;
  trivialCount: number;
  autoGeneratedCount: number;
  emptyCount: number;
  mergeCount: number;
  revertCount: number;
  renameOnlyCount: number;
  formatOnlyCount: number;
  massReformatCount: number;
}

// Full CQI Result
export interface CQIDetails {
  cqi: number;
  components: ComponentScores;
  penalties: CQIPenalty[];
  baseScore: number;
  penaltyMultiplier: number;
  filterSummary?: FilterSummary;
}

export interface AnalyzedChunk {
  id: string;
  authorEmail: string;
  authorName: string;
  classification: string;
  effortScore: number;
  reasoning: string;
  commitShas: string[];
  commitMessages: string[];
  timestamp: string;
  linesChanged: number;
  isBundled: boolean;
  chunkIndex: number;
  totalChunks: number;
  isError?: boolean;
  errorMessage?: string;
}

export interface AnalysisError {
  id: string; // Reuse chunk ID
  authorEmail: string;
  timestamp: string;
  errorMessage: string;
  commitShas: string[];
}

export interface OrphanCommit {
  commitHash: string;
  authorEmail: string;
  authorName: string;
  message: string;
  timestamp: string;
  linesAdded: number;
  linesDeleted: number;
}

export interface Team {
  id: string;
  teamName: string;
  tutor: string;
  submissionCount?: number;
  students: Student[];
  cqi?: number;
  isSuspicious?: boolean;
  cqiDetails?: CQIDetails;
  subMetrics?: SubMetric[];
  basicMetrics?: BasicMetrics;
  analysisHistory?: AnalyzedChunk[];
  orphanCommits?: OrphanCommit[];
}
