= Related Work
Courses like ITP often integrate team-based learning activities, such as group projects, to promote student engagement, better academic performance and social dynamics within teams @michaelsen2004tbl. At the same time, during collaborative assignments students may participate unequally or engage in social loafing, which makes grading more difficult for instructors @kopec2023impact. Educational researchers are increasingly exploring how large language models (LLMs) like GPT-5 could help mitigate some of these challenges, driven by the models' improved performance on coding and other complex tasks @singh2025openaigpt5card. However, the application of LLMs for grading and providing feedback on collaborative team projects remains underexplored @kasneci2023llmsinedu. This section reviews related work on team-based learning and their methods to assess collaboration in software engineering education, measure student code contributions, automate code quality assessment and analyze code using LLMs. We will highlight any key findings and gaps in the literature that Harmonia aims to address.


== Assessment of Collaboration in Software Engineering Education
Collaboration in software engineering education refers to the coordinated effort of team members working toward a shared development goal, encompassing code contributions, communication and shared ownership of artifacts @hundhausen2023combining @ferrao2025llm.

Hundhausen et al. approached this subject by analyzing code contributions using GitHub data, as well as communication and ownership using team chat logs and peer evaluations @hundhausen2023combining. In particular, they extracted the number of commits, number of assigned and closed GitHub issues and the amount of contributed code via the GitHub GraphQL API and analyzed contribution equality by computing the Gini Index. To assess the communication quality and frequency, they tracked the number of messages and words per team member. Finally, the researchers requested students to rate their peers' contribution to the team goals, quality of work and more using the CATME system.

While the GitHub contribution metrics positively correlate with the peer evaluation scores, the authors acknowledge that peer evaluations are subjective and that the GitHub data may not capture all forms of contribution, including design decisions, testing efforts or documentation work. Given that unequal contributions are common and negatively affect grades and collaboration quality @kopec2023impact, there is a need for metrics that capture not only the quantity but also the quality of contributions, while remaining robust to manipulation (e.g. trivial commits) and subjectivity in peer evaluations. We address this need with the Contribution Quality Index (CQI), introduced in @cqi. For communication, they relied on activity-based measurements without considering the semantic content of interactions, unlike more direct forms of collaboration assessment like tutor-observed pair programming (see @pp). Additionally, relying on GitHub issues as a metric makes the approach platform-dependent, limiting its applicability in contexts where GitHub is not used or where issue tracking is not a common practice. 

== Mining Software Repositories and Metrics for Measuring Contributions
Educators in software engineering frequently rely on code contributions to assess student performance @hundhausen2023combining, making Mining Software Repositories (MSR) and associated metrics particularly relevant.
MSR approaches include analyzing version control systems, for example Git, to extract information about code contributions, commit history and other relevant data @hassan2008repomining.

// Need for effort
Chen et al. proposed an automated programming assessment system that leverages Git commits and build logs to statically analyze and evaluate student contributions @chen2022codequality. Their approach focuses on monitoring how the code quality improves and who participates actively within the team project. The authors demonstrate that these metrics can support detecting free-riding behavior. However, the approach primarily focuses on quantitative and quality-based metrics, with limited modeling of collaboration dynamics, for instance shared ownership. Hundhausen et al. address this by employing the Gini Index to measure contribution equality, but this metric is still based on aggregate contribution data and does not capture semantic effort, like code complexity and novelty @hundhausen2023combining.

// Need for temporal spread
Furthermore, Hamer et al. employed Git-based metrics to explicitly examine temporal contribution patterns @hamer2021usinggit. They showed that students often contribute unevenly over time, concentrating their activity near deadlines. This result shows that temporal analysis reveals aspects of collaboration behavior that aggregate contribution metrics might miss.

// LoC Balance and Ownership
As already discussed, most existing approaches rely on Git commit counts, lines of code and activity frequency to assess contributions @hundhausen2023combining @chen2022codequality @hamer2021usinggit. However, these methods operate at the commit or user level and might fail to capture fine-grained ownership of code artifacts. While recent work by Ferrao et al. incorporates line-level attribution using git blame to support LLM-based contribution summarization, such techniques are not yet commonly used for systematically analyzing shared ownership or collaboration patterns across team members @ferrao2025llm.

== Code Quality and Automated Assessment Systems
In contrast to systems that support instructors in evaluating student performance, student-facing approaches give immediate feedback to help students improve their code quality.
Krusche et al. developed the tool Artemis, which automatically tests student code for correctness and performs static analysis to identify style issues and programming errors @krusche2018artemis. This feedback encourages students to adopt clean and maintainable coding practices.
Similarly, Chen et al.'s automated programming assessment system employs the linters and style analyzers HTMLHint, Stylelint and SonarQube, to guide students with their code style and quality in real time @chen2022codequality. 
Both systems effectively encourage students to address issues early and iteratively refine their code through resubmissions, helping them identify and correct specific problems. Their results showcase that such systems can effectively support the reduction of coding errors and the overall improvement of code quality over time. Building on these approaches, recent work has also explored the use of LLMs to provide more flexible and context-aware analyses of code and contributions for both students and instructors.

== LLM-Based Support for Code Review and Contribution Analysis
Ferrao et al. proposed an LLM-driven approach to summarize individual contributions in team software projects by analyzing version control data @ferrao2025llm. Their system leverages repository mining techniques combined with git blame to extract line-level contributions, which are then processed through a multi-stage pipeline to generate natural language summaries of each student's work. The authors' results indicated that the generated summaries are generally consistent with actual student activities and can support both instructors and teams in monitoring project progress. However, the researchers noted that the system may misrepresent contribution quality, as even small or irrelevant contributions were sometimes inflated, leading students who performed more substantial work to feel disadvantaged.

Targeting a different area of software engineering education, Sölch and Krusche propose an LLM-based system, Athena, that automatically gives feedback on UML modeling tasks @soelch2026scaling. Athena generates rubric-aligned feedback on modeling correctness and design quality, supporting human graders in the assessment process and students in their learning process. Unlike code-focused systems, the approach operates on conceptual models rather than source code. Although it does not address traditional code quality aspects, such as style or maintainability, it demonstrates the potential of LLMs to provide detailed feedback on design artifacts, which are also crucial in software engineering education. The tool also presented a good integration opportunity for our student view (elaborated in @student_view), which extends Athena by complementing the existing functionality with LLM-based code quality suggestions.

In contrast, Ramesh et al. explored the use of LLMs for automated code review in an industrial setting, combining static program analysis with prompt-based evaluation of code changes @ramesh2025ericsson. Although the authors don't focus on education, their approach generates concise and context-aware review comments for modified code segments, demonstrating how LLMs could generally support development teams by identifying potential issues and improving code quality. However, the system primarily targets code-level correctness and maintainability and does not consider collaboration aspects like contribution balance or team dynamics.

Overall, prior work has explored a range of approaches to assessing student contributions in team-based software engineering projects, including repository mining techniques, code quality analysis and more recently, LLM-based summarization and feedback systems. While these approaches provide valuable insights into individual participation, code quality and project progress, they largely rely on either quantitative activity metrics or descriptive analyses. As a result, they fail to capture important aspects of collaboration, such as the semantic quality of contributions, the balance of effort among team members and the extent of shared ownership of code artifacts. Furthermore, existing approaches either focus on instructor-facing assessment or student-facing feedback, but rarely integrate both perspectives into a unified framework. These limitations highlight the need for a more comprehensive approach to assessing collaboration quality, which Harmonia bridges.

