= Related Work
Team-based learning, e.g. in the form of group projects or collaborative assignments, is an integral part of many educational settings like the ITP course, because it promotes student engagement, better academic performance and social dynamics within teams @michaelsen2004tbl. However, it also presents challenges not only to the students, such as unequal participation and social loafing, but also consequently grading difficulties to the instructors @kopec2023impact. Additionally, LLMs have peaked educational researchers' interest in recent years, especially with their increasing ability to reason and analyze complex information like code @singh2025openaigpt5card. However, the application of LLMs in team-based learning contexts remains underexplored, particularly in terms of how they can assist in grading and providing feedback on team assignments @kasneci2023llmsinedu. This section reviews related work on team-based learning, in particular methods used to assess collaboration in Software Engineering education, measure student contributions, automate code quality assessment and analyze and review code using LLMs. We will highlight any key findings and gaps in the literature that Harmonia addresses.


== Assessment of Collaboration in Software Engineering Education
Collaboration in software engineering education refers to the coordinated effort of team members working toward a shared development goal, encompassing code contributions, communication and shared ownership of artifacts @hundhausen2023combining @ferrao2025llm.

Hundhausen et al. approached this subject by analyzing code contributions through GitHub data and the more subjective aspects like communication and ownership through team communication chat logs and peer evaluations @hundhausen2023combining. For the code, they used the GitHub GraphQL API to extract the number of commits, number of assigned and closed GitHub issues and amount of code contribution and compute the Gini Index of contribution equality. For the communication they used exclusively number of messages and words per team member and frequency. The researchers gathered peer evaluation data through the CATME system, where students rated each others contribution to the team goals, quality of work and more.

While the GitHub contribution metrics strongly correlated with the peer evaluation scores, the collection methods for code, communication and peer review data are respectively strongly activity-based, qualitative and subjective, which may fail to capture the full picture of collaboration and contribution in team-based learning contexts. Since unequal contributions are common and negatively affect grades and collaboration quality @kopec2023impact, there should be an Contribution Quality Index that captures not only the quantity, but also the quality of collaboration and that is resistant to manipulation, e.g. by committing trivial changes like documentation updates, or to subjectivity, for example happening in peer evaluations. Additionally, relying on GitHub issues as a metric makes the approach platform-dependent, limiting its applicability in contexts where GitHub is not used or where issue tracking is not a common practice. 

== Repository Mining and Metrics for Measuring Contributions
Given that educators in the software engineering field often strongly rely on code contributions when assessing student performance @hundhausen2023combining, it is worth taking an even deeper look into repository mining and statistically-computed metrics.
Repository mining involves analyzing version control systems, such as Git, to extract information about code contributions, commit history and other relevant data @hassan2008repomining.

// Need for effort
Chen et al. propose an automated programming assessment system that leverages Git commits and build logs to statically analyze and evaluate student contributions @chen2022codequality. Their approach focuses on monitoring how the code quality improves and who participates actively within the team project. The authors demonstrate that such metrics can support the detection of free-riding behavior. However, the approach primarily relies on quantitative activity measures and does not consider collaboration dynamics such as shared code ownership or quality of the code content. Hundhausen et al. try to mitigate this by employing the Gini Index to measure contribution equality, but this metric is still based on aggregate contribution data and does not capture semantic effort, which would entail additional metrics like complexity and novelty @hundhausen2023combining.

// Need for temporal spread
Similarly, Hamer et al. employ Git-based metrics, like commits, merges and code churn, to analyze student contributions, but greatly emphasizes temporal contribution patterns @hamer2021usinggit. Their work highlights that contribution patterns are often uneven over time, with bursts of activity concentrated near deadlines. This temporal perspective provides additional insight into collaboration behavior that is not captured by aggregate contribution metrics.

// LoC Balance and Ownership
Most existing approaches rely on Git-derived metrics such as commit counts, lines of code, and activity frequency to assess contributions @hundhausen2023combining @chen2022codequality @hamer2021usinggit. However, these methods operate at the commit or user level and do not capture fine-grained ownership of code artifacts. While recent work by Ferrao et al. incorporates line-level attribution using git blame to support LLM-based contribution summarization, such techniques are not commonly used for systematically analyzing shared ownership or collaboration patterns across team members @ferrao2025llm.

== Code Quality and Automated Assessment Systems
While prior work primarily focuses on instructor-facing assessment, student-facing approaches aim to provide immediate feedback to the students to help them improve their code quality 
The automated programming assessment system that Chen at al. presented employs linters and style analyzers, like HTMLHint, Stylelint and SonarQube, to give real-time feedback directly to the students @chen2022codequality. The immediate feedback students receive encourages them to not wait until final grading to address style and quality issues, fostering an iterative learning process where resubmissions are encouraged. This approach emphasizes actionable feedback, allowing students to identify specific style and quality issues in their code and make improvements accordingly.

Their results show that such systems can effectively support the reduction of coding errors and the overall improvement of code quality over time.
Krusche and Brügge use a similar approach for coding exercises @krusche2018artemis. The tool Artemis not only tests automatically solutions for correctness, but also employs static analysis to provide feedback on code style and programming errors, encouraging students to adopt clean and maintainable coding practices.


== LLM-Based Support for Code Review and Contribution Analysis
Ferrao et al. propose an LLM-based approach to summarize individual contributions in team software projects by analyzing version control data @ferrao2025llm. Their system leverages repository mining techniques combined with git blame to extract line-level contributions, which are then processed through a multi-stage pipeline to generate natural language summaries of each student's work. The results indicate that the generated summaries are generally consistent with actual student activities and can support both instructors and teams in monitoring project progress. However, the approach remains primarily descriptive, focusing on summarizing contributions rather than evaluating their quality or balance. In particular, it does not provide formal metrics for assessing contribution equality or collaboration patterns and the generated summaries may overemphasize minor tasks, such as comments and documentation updates, while omitting or misrepresenting more substantial work. 

Sölch and Krusche propose an LLM-based system for automated feedback on UML modeling tasks for students @soelch2026scaling. The system generates rubric-aligned feedback on modeling correctness and design quality, supporting human graders in the assessment process. Unlike code-focused systems, the approach operates on conceptual models rather than source code. Although it does not address traditional code quality aspects such as style or maintainability, it demonstrates the potential of LLMs to provide detailed feedback on design artifacts, which are also crucial in software engineering education. The tool also presents a good integration opportunity for our approach, which could extend Athena by complementing the existing functionality with code-focused analysis.

