= Related Work
Educational researchers increasingly explore how large language models (LLMs) like GPT-5 can help mitigate some of the challenges described above, driven by the models' improved performance on coding and other complex tasks @singh2025openaigpt5card. The application of LLMs for grading and providing feedback on collaborative team projects remains largely unexplored @kasneci2023llmsinedu. This section reviews related work on methods to assess collaboration in computer science education, measure student code contributions, automate code quality assessment and analyze code using LLMs, highlighting gaps in the literature that the following sections aim to address.


== Assessment of Collaboration in Computer Science Education
Collaboration in computer science education refers to the coordinated effort of team members working toward a shared development goal, encompassing code contributions, communication and shared ownership of artifacts @ferrao2025llm. Hundhausen et al. analyzed code contributions using GitHub data, communication through team chat logs, and ownership through peer evaluations @hundhausen2023combining. They extracted commit counts, GitHub issues and contributed code via the GitHub GraphQL API, then measured contribution equality using the Gini Index. They also tracked messages per team member and requested peer ratings through the CATME system.

The GitHub contribution metrics positively correlate with peer evaluation scores, yet the authors acknowledge that peer evaluations remain subjective and may not capture all forms of contribution such as design decisions or testing efforts @hundhausen2023combining. Unequal contributions occur frequently and negatively affect grades and collaboration quality @kopec2023impact, creating a need for metrics that capture both the quantity and quality of contributions while remaining robust to manipulation (e.g. trivial commits). We address this need with the Contribution Quality Index (CQI), introduced in @cqi. Hundhausen et al. also relied on activity-based measurements for communication without considering semantic content, unlike more direct assessment forms like tutor-observed pair programming (see @pp). Relying on GitHub issues as a metric also makes the approach platform-dependent.

== Mining Software Repositories and Metrics for Measuring Contributions
Mining Software Repositories (MSR) approaches analyze version control systems to extract information about code contributions, commit history and other relevant data @hassan2008repomining. Chen et al. proposed an automated programming assessment system that leverages Git commits and build logs to statically analyze student contributions and monitor how code quality improves over the project @chen2022codequality. Their metrics can support detecting free-riding behavior, yet the approach primarily targets quantitative metrics with limited modeling of collaboration dynamics such as shared ownership.

Hamer et al. employed Git-based metrics to examine temporal contribution patterns and showed that students often concentrate their activity near deadlines @hamer2021usinggit. Their results demonstrate that temporal analysis reveals collaboration behavior that aggregate metrics miss. Most existing approaches operate at the commit or user level and fail to capture fine-grained ownership of code artifacts. Ferrao et al. incorporate line-level attribution using git blame to support LLM-based contribution summarization, but such techniques are not yet commonly used for analyzing shared ownership across team members @ferrao2025llm.

== Code Quality and Automated Assessment Systems
In contrast to systems that support instructors in evaluating student performance, student-facing approaches give immediate feedback to help students improve their code quality.
Krusche and Seitz developed the tool Artemis, which automatically tests student code for correctness and performs static analysis to identify style issues and programming errors @krusche2018artemis. This feedback encourages students to adopt clean and maintainable coding practices.
Similarly, Chen et al.'s automated programming assessment system employs the linters and style analyzers HTMLHint, Stylelint and SonarQube, to guide students with their code style and quality in real time @chen2022codequality. 

Both systems effectively encourage students to address issues early and iteratively refine their code through resubmissions, helping them identify and correct specific problems. Their results showcase that such systems can effectively support the reduction of coding errors and the overall improvement of code quality over time. Building on these approaches, recent work has also explored the use of LLMs to provide more flexible and context-aware analyses of code and contributions for both students and instructors.

== LLM-Based Support for Code Review and Contribution Analysis
Ferrao et al. proposed an LLM-driven approach to summarize individual contributions in team software projects @ferrao2025llm. Their system combines repository mining with git blame to extract line-level contributions, which a multi-stage pipeline processes into natural language summaries. The generated summaries align with actual student activities and can support monitoring project progress, though the pipeline sometimes inflated small contributions, leading students who performed more substantial work to feel disadvantaged.

Sölch and Krusche propose Athena, an LLM-based system that gives feedback on UML modeling tasks in software engineering education @soelch2026scaling. Athena generates rubric-aligned feedback on modeling correctness and design quality, supporting both graders and students. The approach operates on conceptual models rather than source code, yet it demonstrates the potential of LLMs to provide detailed feedback on design artifacts. The tool also presented a good integration opportunity for our student view (elaborated in @student_view), which extends Athena with LLM-based code quality suggestions.

Ramesh et al. explored LLMs for automated code review in an industrial setting, combining static program analysis with prompt-based evaluation of code changes @ramesh2025ericsson. Their approach generates context-aware review comments for modified code segments, demonstrating how LLMs can support development teams in identifying potential issues. The system targets code-level correctness and maintainability and does not consider collaboration aspects like contribution balance or team dynamics.

Prior work covers repository mining, code quality analysis and LLM-based feedback systems, yet these approaches largely rely on quantitative activity metrics or descriptive analyses. They do not capture the semantic quality of contributions, the balance of effort among team members, or the extent of shared code ownership. These limitations motivate the development of a tool that combines collaboration metrics with transparent evidence across all teams.
